# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Docs Build and Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Output files
        run: |
         cd "$GITHUB_WORKSPACE"
         ls -lthr 
      - name: Install dependencies
        uses: pnpm install
      - name: Build Project
        id: Build
        run: |
          export CI="false"
          pwd
          ls -lthr
          npm run build
          pwd
          ls -lthr
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: .
          if-no-files-found: error