
name: PR

on:
  push:
    branches: [ main , master ]

defaults:
  run:
    shell: bash -leo pipefail {0}
jobs:
  PR:
    uses: prateekarora121/central-github-action/.github/workflows/main.yml@main
    
  
